name: "Create pull requests for all forks"

on:
  push:
    branches:
      - main

jobs:
  create_pull_requests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - name: Get fork list
        id: get_forks
        uses: actions/github-script@v3
        with:
          script: |
            const forks = github.repos.listForks({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            return JSON.stringify(forks.data); // Возвращаем строку JSON
      - name: Create pull request for each fork
        uses: actions/github-script@v3
        with:
          script: |
            const forks = JSON.parse(${{ steps.get_forks.outputs.forks }}); // Парсим строку JSON
            const repoName = context.repo.repo;
            for (const fork of forks) {
              const forkOwner = fork.owner.login;
              const forkName = fork.name;
              console.log(Creating pull request for ${forkOwner}/${forkName});
              github.pulls.create({
                owner: forkOwner,
                repo: forkName,
                title: 'Update from upstream',
                head: ${context.repo.owner}:${context.ref},
                base: 'main',
              });
            }
